import type { List, Task } from './task';

/**
 * Persistence boundary. The Tauri implementation talks to SQLite in the Rust
 * process; the browser implementation (used by `vite dev` outside Tauri)
 * keeps data in localStorage. IDs are generated by the caller.
 */
export interface TaskRepository {
  readonly kind: 'tauri' | 'browser';

  listLists(): Promise<List[]>;
  createList(list: List): Promise<List>;
  updateList(list: List): Promise<List>;
  deleteList(id: string): Promise<void>;

  listTasks(): Promise<Task[]>;
  /** Insert-or-replace. Used for create, update and undo-of-delete. */
  saveTask(task: Task): Promise<Task>;
  deleteTask(id: string): Promise<void>;
  /** Rewrites `position` for every id, in order. */
  reorderTasks(listId: string, orderedIds: string[]): Promise<void>;

  /** Atomically inserts lists and tasks. Only called on an empty database. */
  seed(lists: List[], tasks: Task[]): Promise<void>;

  /** Absolute directory where the database lives. */
  dataPath(): Promise<string>;
}
