import type { Region, Task } from './task';

/**
 * Persistence boundary. The Tauri implementation talks to SQLite in the Rust
 * process; the browser implementation (used by `vite dev` outside Tauri)
 * keeps data in localStorage. IDs are generated by the caller.
 */
export interface TaskRepository {
  readonly kind: 'tauri' | 'browser';

  getRegions(): Promise<Region[]>;
  createRegion(region: Region): Promise<Region>;
  updateRegion(region: Region): Promise<Region>;
  /** Also deletes the region's tasks. */
  deleteRegion(id: string): Promise<void>;

  getTasks(): Promise<Task[]>;
  /** Insert-or-replace. Used for create, update and undo-of-delete. */
  saveTask(task: Task): Promise<Task>;
  deleteTask(id: string): Promise<void>;
  /** Rewrites `position` for every id, in order. */
  reorderTasks(regionId: string, orderedIds: string[]): Promise<void>;

  /** Atomically inserts regions and tasks. Only called on an empty database. */
  seed(regions: Region[], tasks: Task[]): Promise<void>;

  /** Absolute directory where the database lives. */
  dataPath(): Promise<string>;
}
