import type { Space, Task } from './task';

/**
 * Persistence boundary. The Tauri implementation talks to SQLite in the Rust
 * process; the browser implementation (used by `vite dev` outside Tauri)
 * keeps data in localStorage. IDs are generated by the caller.
 *
 * Domain types are `Space` / `spaceId`. The wire format — SQLite tables, columns, Tauri command
 * names and the localStorage blob — still says `region`, and `src/data/repository.ts` is the only
 * place that mapping exists. Do not let `region` leak above this interface.
 */
export interface DataRepository {
  readonly kind: 'tauri' | 'browser';

  getSpaces(): Promise<Space[]>;
  createSpace(space: Space): Promise<Space>;
  updateSpace(space: Space): Promise<Space>;
  /** Also deletes the space's tasks. */
  deleteSpace(id: string): Promise<void>;

  getTasks(): Promise<Task[]>;
  /** Insert-or-replace. Used for create, update and undo-of-delete. */
  saveTask(task: Task): Promise<Task>;
  deleteTask(id: string): Promise<void>;
  /** Rewrites `position` for every id, in order. */
  reorderTasks(spaceId: string, orderedIds: string[]): Promise<void>;

  /** Atomically inserts spaces and tasks. Only called on an empty database. */
  seed(spaces: Space[], tasks: Task[]): Promise<void>;

  /** Absolute directory where the database lives. */
  dataPath(): Promise<string>;
}
